### ISSUE TITLE
No 'version' key in the manifest file for custom integration 'scout_alarm'

### ISSUE THREAD

**Issue by shiitbiird** [andyalm/homeassistant-scout-alarm#11]
Breaking changes w/ the latest HA update. Im receiving this error in the logs when trying to install:

Logger: homeassistant.loader
Source: loader.py:786
First occurred: 6:39:14 PM (1 occurrences)
Last logged: 6:39:14 PM

No 'version' key in the manifest file for custom integration 'scout_alarm'. As of Home Assistant 2021.6, this integration will no longer be loaded. Please report this to the maintainer of 'scout_alarm'

**Comment by shiitbiird** [comment]
Scratch that... fixed it.

**Comment by jakecolman** [comment]
This will not be an issue until a few versions from now.

**Comment by shiitbiird** [comment]
Yeah, I'm an idiot and was able to get the error message to go away by deleting my YAML config and reconfiguring through the UI. Sorry about that!
