### ISSUE TITLE
Smoke alarms and glass break work

### ISSUE THREAD

**Issue by JDStudiosAuto** [andyalm/homeassistant-scout-alarm#14]
In addition to the door panel and door sensors, the glass break sensor and smoke detectors are also working. The glass break sensor also adds entities for temp and humidity.

**Comment by jakecolman** [comment]
Actually, pretty much all the sensor support I added should include entities for temp and humidity.  Let me know if you have any suggestions for any functionality I may have missed.

**Comment by andyalm** [comment]
Is the purpose of this issue to call out that the documentation/README needs to be updated?

**Comment by jakecolman** [comment]
Closing this issue since we have implemented support and started updating the documentation.
