### ISSUE TITLE
implements device state attributes

### ISSUE THREAD

**Issue by npentell** [andyalm/homeassistant-scout-alarm#20]
Good evening.  First off, love the addon.  I am, however, getting a warning in my logs.  Not sure if it was with the recent update or if it has been showing for a while.  
`2021-12-21 21:17:58 WARNING (MainThread) [homeassistant.helpers.entity] Entity alarm_control_panel.nick_s_house (<class 'custom_components.scout_alarm.alarm_control_panel.ScoutAlarmControlPanel'>) implements device_state_attributes. Please report it to the custom component author.`

Got any thoughts?  Thanks a lot.

**Comment by jakecolman** [comment]
This is new to the 2021.12 release.  Seems they deprecated the device_state_attributes and want it renamed to extra_state_attributes.  The warning is harmless for now.  I will update the code and merge it as soon as I hear back from Andy about my last merge request.  Thanks for reporting this.

**Comment by npentell** [comment]
np and thanks a lot!

**Comment by jakecolman** [comment]
This issue has been fixed
